Storybook react v6
flow-typed/flow-typed pull request #3907
Opened 2020-09-26 06:57 UTC by Brianzchen

- Links to documentation: https://www.npmjs.com/package/@storybook/react
- Link to GitHub or NPM: https://www.npmjs.com/package/@storybook/react
- Type of contribution: new definition

Other notes:
`Context` type is not well documented and was derived from what was printed in the console
<img width="784" alt="Screen Shot 2020-09-26 at 4 54 13 pm" src="https://user-images.githubusercontent.com/12436524/94332475-0b60ae80-0019-11eb-8564-d8f336f45c23.png">

2020-09-26 08:28 UTC, Brianzchen commented
@pascalduez I was hoping to remove the describe/it blocks to move `module` to top level but I'm still getting errors. Any recommendations?

2020-09-28 15:22 UTC, AndrewSouthpaw commented
> I was hoping to remove the describe/it blocks to move module to top level but I'm still getting errors. Any recommendations?

Hmm I would imagine that wouldn't work because it's a restriction of ES6 syntax. Were the tests working before? I'm wondering if they just never worked...

I haven't worked with storybook, but could you bundle it as an imported constant rather than referring explicitly to `module`?

2020-09-28 20:47 UTC, Brianzchen commented
> > I was hoping to remove the describe/it blocks to move module to top level but I'm still getting errors. Any recommendations?
> 
> Hmm I would imagine that wouldn't work because it's a restriction of ES6 syntax. Were the tests working before? I'm wondering if they just never worked...
> 
> I haven't worked with storybook, but could you bundle it as an imported constant rather than referring explicitly to `module`?

I don't think it ever worked, I got errors as soon as I started working on it. I'm now thinking maybe I'll just declare a var for a fake module and use that instead

2020-10-03 04:36 UTC, AndrewSouthpaw requested changes
Nice, I'm glad that worked. Would you be able to reinstate the `describe/it` blocks?

2020-10-03 05:34 UTC, Brianzchen commented
@AndrewSouthpaw all done!

2020-10-05 14:19 UTC, pascalduez commented
I swear this worked perfectly back in time, maybe something changed at the Flow level.   
But if we can't test with real world usage how can we assert this is even working, something doesn't click here, I'm not to keen on the f`akeModule` thing. Sorry for not bringing much help here, I would need to delve in to better understand...

2020-10-05 19:05 UTC, Brianzchen commented
> I swear this worked perfectly back in time, maybe something changed at the Flow level.
> But if we can't test with real world usage how can we assert this is even working, something doesn't click here, I'm not to keen on the f`akeModule` thing. `module` is a Node global. Sorry for not bringing much help here, I would need to delve in to better understand...

Can I leave this with you to figure out? I've done my best and tried multiple ways. You can check my previous test runs to see the behaviours that occurred.

2020-10-06 08:27 UTC, pascalduez commented
> Can I leave this with you to figure out?

Will try, but current personal situation is quite tense, probably won't be able to invest much time in it soon.

2020-10-06 20:10 UTC, Brianzchen commented
Yeah I don't mind keeping this around. Given that storybook v6 came out recently it'd be great to supply users with defs but v5 still gets the job done at least

2020-10-14 19:27 UTC, AndrewSouthpaw commented
Alright. Sounds like the decision for now is to leave this PR open until @pascalduez has time later to investigate.

2020-11-07 09:32 UTC, Brianzchen commented
@pascalduez any news on this one?

2021-02-21 09:54 UTC, pascalduez commented on definitions/npm/@storybook/react_v6.x.x/flow_v0.25.x-/react_v6.x.x.js
> +  declare function setAddon(addon: Object): void;
`Object` to be replaced.

2021-02-21 09:55 UTC, pascalduez commented on definitions/npm/@storybook/react_v6.x.x/test_react_v6.x.x.js
> +import React from 'react';
```suggestion
import * as React from 'react';
```

2021-02-23 17:38 UTC, merged