Add Effector typings
flow-typed/flow-typed pull request #4376
Opened 2022-08-20 11:39 UTC by igorkamyshev

Reopened #4372 

- Links to documentation: https://effector.dev
- Link to GitHub or NPM: https://github.com/effector/effector
- Type of contribution: new definition

Other notes:

Hello, folks. I'm Igor, Effector Core Team member. We are preparing the new major release (v23) and have decided to move Flow-typings from the main repo of Effector to this repository.

Please consider merging my PR.

Tracking issue in Effector — https://github.com/effector/effector/issues/755

2022-08-20 11:49 UTC, igorkamyshev commented
Hello, @Brianzchen!

Thanks for your review in previous PR. I have fixed directory structure, rename branch and add some cases for basic scenario.

Could you check it one more time, please?

2022-08-21 00:45 UTC, Brianzchen requested changes

2022-08-21 00:45 UTC, Brianzchen commented on definitions/npm/effector-react_v22.x.x/flow_v0.83.x-/effector-react_v22.x.x.js
> +  //@flow strict
don't need this at all in the file. But also flow pragmas should only be referenced at the top of the file. I imagine if you removed this everything should still work

2022-08-21 00:45 UTC, Brianzchen commented on definitions/npm/effector-react_v22.x.x/flow_v0.83.x-/effector-react_v22.x.x.js
> +  export type StoreConsumer<State> = ComponentType<{|
All these exports are missing the `declare` keyword which is necessary inside module declarations.

2022-08-21 00:45 UTC, Brianzchen commented on definitions/npm/effector_v22.x.x/flow_v0.83.x-/effector_v22.x.x.js
> +  //@flow strict
can remove this too

2022-08-21 00:52 UTC, Brianzchen commented
Thank you @igorkamyshev. Since these are definitions for your own library so as long as basic standards are maintained I'm happy to merge.

You've just got a few minor syntax failures. To solve this, you can run `./quick_run_def_tests.sh` in the root to test locally. But before this you want to build the the cli under `main` with `yarn && yarn build` in `/cli`

2022-12-20 06:42 UTC, closed without merging

2022-12-21 15:26 UTC, sergeysova commented
@igorkamyshev Why you closed this?

2022-12-22 05:25 UTC, igorkamyshev commented
> @igorkamyshev Why you closed this?

Discussed it in private conversation with effector team.